### ISSUE TITLE
C182T: EIS should display electrical bus load; SBY Battery to be modelled

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#355]
- [ ] The EIS display currently does not show the electrical load, but a static value +110.
- [ ] The Standby battery system is not modelled.

@stuartbuchanan if you can guide me to the piece of code on how i can wire the values to the model, i will happily do that; and also model the standby battery system.

See also #354

**Comment by stuartbuchanan** [comment]
@hbeni I've fixed the EIS display, but haven't modeled the standby battery.

**Comment by hbeni** [comment]
@stuartbuchanan

> The EIS display currently does not show the electrical load, but a static value +110.

You fixed this?

And its just the internal model that is missing?
If so: What property is read out, so I can make the battery model and wire it?

And: I think I should reopen the ticket?

**Comment by wlbragg** [comment]
I'm needing this information as well.

**Comment by wlbragg** [comment]
@hbeni 
I didn't know where to post this question to you so I figured this is as good a place as any. also because I would like to see the electrical load in the fg1000 EIC as well.

But here is an unrelated question. I was reviewing the electrical systems of both the c171p and fg1000 variant. i have long questioned how the 'load" is calculated and that it is intrinsically wrong if you think you cane use the real anticipated amp draw. Because bus_voltage / amps returns less load with higher amp draw. So I looked at your electrical and notices you caught that and tried to work around it. I noticed for example the nav light is like 5 and the landing light is like .11. This is exactly what I am referring to. Where did you come up with that conversion of figuring out the landing light should be .11?
you know what I think? I think somewhere along the line that maybe the load calc per electrical instrument get reversed accidentally. My reasoning is that ever calculation I have seen is the opposite. I read in documentation on the subject that the calculation is...
watts / bus_volts
and to get watts...
amps * bus_volts

In the electrical.nas comment is states
# Passing in positive amps means the battery will be discharged.
# Negative amps indicates a battery charge.

So are we safe to assume we are using amps and not watts?

Anyway, your load numbers appear to be closer to correct than not considering the very strange bus_volts / amps.

By the way, that calculation bus_volts / amps give you resistance. It cannot be correct for this system from my understanding. We really should redo these electrical systems.

**Comment by hbeni** [comment]
> We really should redo these electrical systems

I agree :)
However I think I am not the current person to question, i just added to the electrical system. It was already in piece die the most part when I started contributing.

I think the main objective was to have some ekectrical system drawing energy in a reasonable way, to display on the amp gauge and also simulate battery/alternator behaviour.

**Comment by wlbragg** [comment]
@hbeni 
I understand, I'm in the same position. I am working on it right now with a little bit better understanding and I think I may be on to a fix that will at least let you use known amps for the load values VS having to come up with some random conversion. I'll let you know if I am successful. Also note I already extended the battery class to allow for a second backup battery such as is in the fg1000 variant. When I am finished you can look at the fg1000 variants electrical-fg1000.nas. Actually, you can look at that now for the extending portion to get a second battery, just not the battery values such as ampH and such. I haven't pushed those edited values yet or the new load calculation portion.

**Comment by hbeni** [comment]
Great! Thank you!

**Comment by hbeni** [comment]
Ah, btw, the system simulates amps currently

**Comment by wlbragg** [comment]
Kind of, the values you feed per breaker though are not in amps. That is what i am trying to fix. So far I changed them to watts..
draw = amps * bus_volts
then later in the main batt calculations I convert it back to amps
draw / bus_volts
because I think your right and the bat class is using amps
It's really close to working this way, but I think the actual bat class may need some adjustment in its calculation. I'm not quite there yet.

**Comment by hbeni** [comment]
Hm. I didn’t look, but shouldn’t be there a realistic systems class for batteries and alternators in fgaddon?
It’s such an fundamental system needed by nearly any plane, there should really be done utility classes for aircraft devs… in my opinion

**Comment by hbeni** [comment]
Just for the archives; I now modelled the standby battery in Issue #565 / PR #567
