### ISSUE TITLE
Cockpit / plane model LOD 

### ISSUE THREAD

**Issue by MariuszXC** [HHS81/c182s#428]
As observed during today's multiplayer event, FG was displaying low detail model of c182s with high detail interior. 
See screenshots.
https://ibb.co/C6BV58M
https://ibb.co/JzXdhsw
https://ibb.co/jb17cCW
https://ibb.co/jwk6PtV
https://ibb.co/S71ZRWY
[url=https://ibb.co/C6BV58M][img]https://i.ibb.co/68YDRw1/fgfs-20210804201350.jpg[/img][/url]
[url=https://ibb.co/JzXdhsw][img]https://i.ibb.co/4jBfQVn/fgfs-20210804201337.jpg[/img][/url]
[url=https://ibb.co/jb17cCW][img]https://i.ibb.co/HBkmWcx/fgfs-20210804201302.jpg[/img][/url]
[url=https://ibb.co/jwk6PtV][img]https://i.ibb.co/z2VnTd8/fgfs-20210804201254.jpg[/img][/url]
[url=https://ibb.co/S71ZRWY][img]https://i.ibb.co/7NT028M/fgfs-20210804201246.jpg[/img][/url]

Also, there is a couple of interesting lines in console, which may or may not be related:
4560.34 [ALRT]:nasal      Nasal runtime error: nil used in numeric context
 4560.34 [ALRT]:nasal        at ...compile/fg_next/install/flightgear/fgdata/Aircraft/c182s/Models/c182s.ac, line 99
 4560.34 [ALRT]:nasal        called from: ...compile/fg_next/install/flightgear/fgdata/Nasal/globals.nas, line 131
 4560.34 [ALRT]:nasal      Nasal runtime error: nil used in numeric context
 4560.34 [ALRT]:nasal        at ...compile/fg_next/install/flightgear/fgdata/Aircraft/c182s/Models/c182s.ac, line 115
 4560.34 [ALRT]:nasal        called from: ...compile/fg_next/install/flightgear/fgdata/Nasal/globals.nas, line 131
 4560.34 [ALRT]:nasal      Nasal runtime error: nil used in numeric context
 4560.34 [ALRT]:nasal        at ...compile/fg_next/install/flightgear/fgdata/Aircraft/c182s/Models/c182s.ac, line 131
 4560.34 [ALRT]:nasal        called from: ...compile/fg_next/install/flightgear/fgdata/Nasal/globals.nas, line 131
 4560.34 [ALRT]:general    Canvas constructor: node=/canvas/by-index/texture[5]
 4560.34 [INFO]:nasal      C182 immat/registration: initialize multiplayer instance for target_module_id=7
 4560.83 [INFO]:nasal      C182 immat/registration: livery misses canvas immat properties: skipping canvas update.
 4570.09 [INFO]:nasal      c182s livery update
 4570.50 [INFO]:nasal      C182 immat/registration: livery misses canvas immat properties: skipping canvas update.
 4761.53 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/flight[0]/elevator-trim[0]
 4771.53 [INFO]:nasal      c172p livery update
 4966.27 [INFO]:nasal      c172p livery update
 5367.51 [ALRT]:ai         /sim/rendering/static-lod/aimp-bare is <= 0. This should be a delta on top of aimp-detailed in meters mode. setting to 1.
 5367.51 [ALRT]:ai         /sim/rendering/static-lod/aimp-bare is <= 0. This should be a delta on top of aimp-detailed in meters mode. setting to 1.
[... a lot of repeats ...]
5816.90 [ALRT]:ai         /sim/rendering/static-lod/aimp-bare is <= 0. This should be a delta on top of aimp-detailed in meters mode. setting to 1.
 5816.90 [ALRT]:ai         /sim/rendering/static-lod/aimp-bare is <= 0. This should be a delta on top of aimp-detailed in meters mode. setting to 1.

**Comment by hbeni** [comment]
Thanks for reporting it for the Archive, Mariusz!
Closing this as _wontfix_, as already discussed, because its a FGFS core issue.

:information_source: **For the Archives/other users here what we found out:**
- Flightgear distinguishes between an interior and an exterior model.
- You can adjust your LOD (Level Of Detail) settings to hide the detailed exterior model based on range (or display size in pixel).
- If the detailed exterior is not selected, usually a low-poly default model from the FGFS core will be shown instead, to save performance.
- The same goes for the internal detailed model.

So what happens is: When your LOD settings command flightgear to display the detailed interior model, but not the detailed exterior one, you get a mix between default-exterior and detailed-interior.
The default model however has a "wrong" z-axis offset, making it not only sinking into the ground, but also making the detailed cockpit stand out at the roof.
Unfortunately the FGFS default settings trigger this behaviour.

The real fix to this is one, or both of these:
1. The FGFS low poly c182 model needs to be moved up a little, so it corresponds to the detailed cockpit.
2. FGFS should not try to display a detailed cockpit when the detailed exterior is hidden already (this does not make any sense, first the cockpit should go low-poly or hidden, and after that the detailed plane)

Regarding 2.:
Mariusz did find that the behaviour of the "AI/MP interior" slider is reversed: it seems to define the range _from_ which the detailed cockpit is shown, not like intended the max-range where it should be rendered. This very likely affects overall performance because it means that any MP or AI plane will render the cockpit in any distance unless its really close (200 meters in default settings).

**Comment by hbeni** [comment]
> Also, there is a couple of interesting lines in console, which may or may not be related

not related, opened a fresh issue for this: #430
