### ISSUE TITLE
Electrical power limits activating winterization kit.

### ISSUE THREAD

**Issue by wlbragg** [HHS81/c182s#502]
I noticed on the c172p having electrical power applied to the aircraft causes some of the engine properties like rpm and velocities/groundspeed-kt to be active, not at 0. This is allowing some conditions to cause the GUI menu choice to not be "allowed".

This is happening on at least one of the c182 systems, the Winterization Kit.

**Comment by hbeni** [comment]
Winterzation kit needs a stopped propeller, to mimic real life conditions.
Other things need a stopped plane.

That is intentional, but what exactly do you mean by „applying electrical power“?
Are you attaching the ground based generator and that causes the issue you are describing?

**Comment by wlbragg** [comment]
It may only be my computer. 
See [this video](https://github.com/c172p-team/c172p/issues/1398#issuecomment-1675988756)
Notice the properties in the tree that are active even though the aircraft is not running, I only have the batt supplying power.

This is cold and dark in the c182
https://github.com/HHS81/c182s/assets/11069680/97662967-608d-415c-adf8-b2985b53364c

The problem is, even with the batt off the rmp property is active and and I can't ever activate the winter kit. Same for other features in the c172p.

**Comment by hbeni** [comment]
Will investigate once i‘m at home again

**Comment by wlbragg** [comment]
It was PHTO live weather. I tried a couple other airports, switched to Fair weather. Then tried Basic weather. All the same thing.

**Comment by dany93** [comment]
Instead, another more realistic (and easy to implement) condition would be (at least) both magnetos at 0.
IRL, prior to do such interventions close to the propeller, we have BATT OFF, ALT OFF and imperatively Both magnetos OFF.

**Comment by dany93** [comment]
@wlbragg wrote
>how to start the sim with no wind by default

`--wind=190@0`
for 0 kt from 190 deg.

**Comment by dany93** [comment]
In the simulator, the very weak rpm might be due to a propeller windmilling phenomena. By descending with throttle at zero in flight, the propeller spins more rapidly than idle. 
Although impossible IRL for usual winds on the ground.

**Comment by TheFGFSEagle** [comment]
No, you should just allow some margin on the properties - like, allow adding / removing the winter kit below 1 RPM instead of at  0 RPM ! ;)

**Comment by wlbragg** [comment]
>Maybe we also should check for regressions?

I remember that, do you remember where static friction was added?

I don't like rpm as the condition at all.  Technically a pilot installing the kit could potentially move the prop and produce a micro amount of rpm.
I think on the c172p we'll end up using use BATT OFF, ALT OFF and Both magnetos OFF. They are pretty benign and seem appropriate. Even just mags off would be sufficient. WOW and ground speed should also be good, but I am afraid of residual ground speed. causing an unintended failure.

**Comment by TheFGFSEagle** [comment]
> WOW and ground speed should also be good, but I am afraid of residual ground speed. causing an unintended failure.
Would be better IMO - just check if the ground speed is less than 1 kt and you're good !

**Comment by dany93** [comment]
@wlbragg wrote
>do you remember where static friction was added?

It can be added in each engine configuration file
`<static-friction  unit="{HP | WATTS}"> {number} </static-friction>`

It is at 1.5 HP per default.
It is used, changed elsewhere is our c172, if I remember well to simulate an engine clamping in case of overheating.

However, I don't like at all changing this value. Increasing it will give a loss of power and a decrease of the windmilling RPM. These values are good as they are.

> Used to control and slow a windmilling propeller

Not to prevent some propeller rotation due to wind on ground. Even if it probably have this effect.
Using this property is a purely artificial way of preventing propeller rotation due to wind on ground. Just for the sake of simulation. 
And, IMO, inappropriate and useless:
@wlbragg wrote
> the rpm is reading positive. It is actually winding up slowly starting somewhere around 0.00273......

This value in the sim is microscopic and, maybe, not a flaw. Even IRL, we can imagine that the wind can make the propeller rotate by such an undetectable value. Moreover, when someone makes the propeller rotate by hand, the resistance will not be continuous friction but by steps due to cylinder compressions.
When installing the cowl plugs, the pilot will probably rotate the propeller  to have it in a good position. Which is a reason to have at least ALT OFF and both magnetos OFF.
Making the propeller rotate by hand is often done, for diverse reasons.
Propeller RPM = 0 is not at all a good criteria. Focalisation on this is purely a simulation concern. 
@dany93 wrote
>IRL, prior to do such interventions close to the propeller, we have BATT OFF (to prevent the starter from working), ALT OFF and Both magnetos OFF. In a simulator we can add "Aircraft on the ground" (WOW property).

Plus, possibly, aircraft stopped (purely simulation concern too...)

**Comment by hbeni** [comment]
> > Maybe we also should check for regressions?
> 
> I remember that, do you remember where static friction was added?

I think this was the commit:

> commit c5982161d8ac2a8e9407aa4166b5675620121f4f
>     Moved basic friction to engine static-friction
