### ISSUE TITLE
Fuel system

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#52]
Create the fuel system for the C182S according POH as it works completly different to older Cessna single props.
1.)
It should create affect fuel consumption when engaged, depending by mixture and also able to flood the engine.

2.)it should also be affectd by the engine and outside temperature.

**Comment by gilbertohasnofb** [comment]
Also we should make the fuel selector clickable and implement its functioning.

**Comment by HHS81** [comment]
see my answer Issue #107

**Comment by hbeni** [comment]
Today i tried to figure out how it is currently implemented so i can switch to a newly implemented system using a Systems/fuel.xml.
What do i have to disable and reenable to get a starting point?

**Comment by HHS81** [comment]
@hbeni:
To understand, that the C182S has a fuel-injected engine, and doesn't work like older Cessna. 
Short: We can't use the system from the c172p here. 
Please also see #107, I have already started some work.

**Comment by hbeni** [comment]
Thank you, i have noticed it. I did not find any code.
I just found out how to integrate new tanks and make the engine feed from the manifold instead of directly out of the tanks. Also the fuel selector switch is already working :)
I am aware that i cant port the c172 system, but i wanted to study it to get ideas and clarify questions i had.

currently playing with fuel :)

**Comment by HHS81** [comment]
> I just found out how to integrate new tanks and make the engine feed from the manifold instead of directly out of the tanks

That's the easy part :-)
The harder part is making the boost pump; and let fuel-flow rising by full rich mixture; let fuel dissapearso manifold is empty after a while.... :-)

**Comment by HHS81** [comment]
I got the rpm and mp numbers at idling correct, my next step is correct fuel flow numbers. So when you are able to get a fuel injection system to model, that would be cool!

**Comment by hbeni** [comment]
currently fighting with the tank flows not doing what i want.
Priming could be simulated reltively easily: My  plan is to define a manfold "tank" that gets feed by from two places:
a) the mechanical engine pump tranfsers fuel to the manifold (engine feeds from here) when engine is running
b) the electrical pump pumps if on and current is present.
=> The mechanical pump can only fill the manifold to (say arbitrarily) 75% but the elec pump can pump to 100% => if the tank is filled more than (say again arbitrarily 80%), the engine is flooded and should not be able to get started (probably implemented by an engine filter?)

I will file a PR once the basic system is usable. That will give us at least proper handling of the fuel selector. From there i would want to make a second PR with the more advanced features.

**Comment by HHS81** [comment]
Hmmm... some thoughts:

modelling a manifold tank in jsbsim sounds good, you can hide additional btw. in the fuel dialog.
But I would also modelling the fuelline as "tank" and get the mechanical pump and the electrical aux. pump feed from this fuelline. The mechanical pump would linked to the engine rpm, the aux. pump would run by electrical ouput and their output would be each `fdm/jsbsim/propulsion/tank[i]/external-flow-rate-pps` which ever is higher. 
The problem to solve is, that according to the checklist when the aux pump is running and mixture is enriched, fuel flow is rising. It is the same property the engine provides (`fdm/jsbsim/propulsion/engine/...`). It could maybe done by `fdm/jsbsim/propulsion/tank[i]/external-flow-rate-pps` from the aux pump is multplied with the mixture property setting (0-1) and transfered to a new property .`../indicated-fuel-flow-gph`. The image below shows the fuel schematic of the C182S:
![fuelsystem](https://user-images.githubusercontent.com/12649375/29941355-94604e4e-8e92-11e7-9d43-5dacd3d140e3.jpg)

> Is this already in master?

No, I need to make sure that fuel flow and power will match according POH. This needs some time, as I have to check and change properties in runtime for every 2000ft from sealevel up to 14000ft.
It won't affect you work since this is done on engine/ propulsions side and only adjusts the engine itself.

**Comment by HHS81** [comment]
> This needs some time, as I have to check and change properties in runtime for every 2000ft from sealevel up to 14000ft.

Oh, and per every mp-inhg!
And this all for -20° ISA and +20° ISA I found out today....

**Comment by hbeni** [comment]
Thanks for posting the schematics. I already got these from page 7-25 of the POH.
Thank you also for the ideas! What i wonder is, why you would model the pipe from the strainer outlet? My plan was to directly pump from the strainer sump (where also the drain gets modelled). This approach seems simpler to me without compromising the system handling.

Also i wonder what the real-world effects of the aux pump is. According to POH 7-28, the aux pump does not have significant effects on the engine, besides a slight enrichment of the mixture (wich would be nice if modelled, but no priority in my opinion). Very interesting is the description that the aux pump is able to sustain pressure for maximum engine power. That allows us to let the manifold be fed by a simple switch (either engine pump or aux pump must be operating for fuel to flow); special handling is only required in the priming phase.
What bugs me is the following question: since the starter does rotate the engine, this should also drive the engine pump, doesn't it? so why is priming with the aux pump actually needed for? Sholdn't the starter-driven engine pump drive pressurize and transfer fuel to the nozzles and thus make the aux pump priming obsolete?
Also note the information of the POH that usually after engine shutdown there is enough fuel left to let the engine start again (is this true also after the plane was parked some time, thus reestablish the need for aux-pump-priming in this constellation? This i would model by a slow fuel "drain" at the final manifold tank.)
![image](https://user-images.githubusercontent.com/13608602/29965793-67c2185e-8f0f-11e7-92f4-6abc4d5277e9.png)


I also will need some time to came up with a stable system and i'm now at vacation for a week w/o internet access.

**Comment by HHS81** [comment]
> What i wonder is, why you would model the pipe from the strainer outlet? My plan was to directly pump from the strainer sump (where also the drain gets modelled). This approach seems simpler to me without compromising the system handling.

JSBsim is really great in simulating systems, especially the fuel system. The Aux pump will also draw the line with fuel, so my idea was to exactly simulate this, the other idea behind was, that we could model later the breakage of this fuel line when we come to damage simulation. Otherwise you are right, it would be overdone. Nethertheless, we already model the unsused fuel and it is taken in account of the weight, so I'm absolutely fine with your approach.

> Also i wonder what the real-world effects of the aux pump is. [...] since the starter does rotate the engine, this should also drive the engine pump, doesn't it? so why is priming with the aux pump actually needed for? Sholdn't the starter-driven engine pump drive pressurize and transfer fuel to the nozzles and thus make the aux pump priming obsolete?

[Reddit user say: ](https://www.reddit.com/r/flying/comments/40emop/why_are_fuelinjected_lycoming_engines_started/)"Because Moses came from the mountain with Ten Commandments, which became the Cessna checklist: Now the cockpit was dark and cold, silence was over the radios, and the Spirit of God hovered over the controls. And God said, "Mixture: IDLE CUTOFF; Master Switch: ON; Auxiliary Fuel Pump: ON..." 😄  O.k., who ever wrote this, should read the bible again.....

Seriously:
Aircraft engines differs from automobiles engine. Battery and starter are usually smaller and less powerfull due to weight reduction. So the Aux pump supports the engine while starting by adding fuel in the cylinders, so the engine must be less cranked which reduces the load on the starter and battery. Indeed the engine pump would be good enough for pressurizing and transfer fuel at normal days, but will add unnessacary load on the engine, since it needs some several cranks until there is fuel in the cylinders.
Another things is the "vapor lock". At hot weather fuel in the fuel lines will vaporize and lock the lines, so the electric pump will help to overcome.
But why there is no fuel in the cylinders while starting? Because you while shutdown you put the mixture to IDLE CUTOFF: <a href="https://www.pilotsofamerica.com/community/threads/why-do-we-startup-and-shutdown-piston-airplane-engines-the-way-we-do.60067/#post-1178761">Why do we startup and shutdown piston airplane engines the way we do?</a>
And, last but not least: when the engine pump fails, you still have gravity and the aux pump.

> besides a slight enrichment of the mixture (wich would be nice if modelled, but no priority in my opinion)

Possible, I have the code lying around

**Comment by HHS81** [comment]
> I also will need some time to come up with a stable system and i'm now at vacation for a week w/o internet access.

Nice! Enjoy your vacation!
I have you invited as collaborator, I think it will be more easy for you than using a fork.

**Comment by gilbertohasnofb** [comment]
> I have you invited as collaborator, I think it will be more easy for you than using a fork.

Great, so welcome! :smile:

**Comment by hbeni** [comment]
> I have you invited as collaborator, I think it will be more easy for you than using a fork.
Than you very much for your confidence, i try to not mess anything up ;)

I migrated my (previously private) fuelSelector branch over here where i will continue working on the fuel system.

**Comment by hbeni** [comment]
fixed with  6ba98ea
