### ISSUE TITLE
Rudder pedals very sensitive

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#575]
The pedals are much more sensitive than with the 172...
Should that be the case?

Especially with taxiing this is sometimes problematic.

**Comment by hbeni** [comment]
From a first glimpse the nose wheel steering parameters are okay per POH.

* The `/fdm/jsbsim/fcs/rudder-pos-deg` and `-rad` values are nearly doubled compared to the C172p (16° vs. 27°).
* The `aero/coefficient/CYdr` (Side_force_due_to_rudder) is also different (0.115 vs. 0.187)
* The `aero/coefficient/Cndr` (Yaw_moment_due_to_rudder) is also different (-0.0645 vs. table based on `velocities/u-fps` ranging from -0.0604 to -0.0805, having the same for the 'climb' value)


@HHS81 Where do these numbers come from?

**Comment by hbeni** [comment]
@HHS81 aaand: is there a reason, the `Pitch_moment_due_to_elevator_deflection` does not start at `0` too, but with `107.1	-1.029 <!--Approach-->` ?
https://github.com/HHS81/c182s/blob/560a99cc7502bd96f504df021f4b0e02d637e039/c182s.xml#L1890-L1905

**Comment by TheFGFSEagle** [comment]
Uh, yeah, because, when the speed is very low, the effect of t he elevator will also be very low - it increases quadratically with increasing airspeed. If you set it to 0 at u-fps=0, you would kind of converting this to increasing cubically (not exactly - but it helps to get your head around it !). The reason that there are different values at all is because when you fly very slow or very fast, you have different angles of attack, at which the elevator deflection has different strengths of effect - but making that depend on u-fps doesn't make any sense at all, IMO. But you could ask @ysopflying.

**Comment by ysopflying** [comment]
Thanks for the kind mentioning.
aero/coefficient/Cndr is ok with literature (-0.658)
aero/coefficient/CYdr Don't worry! The aircraft are not identical.
/fdm/jsbsim/fcs/rudder-pos-deg What is the POH saying? Could be mechanically different as well.

The separation into approach, climb and cruise takes into account different alpha, maybe flap and Reynolds effects. It could be done way more complex than just three values.
Between 0 and 107.1 there are no values available, so better to stick with the lowest known.
So the table looks fine.

The issue is primarily related to the noise wheel steering or the aerodynamic effect of the rudder?

**Comment by ysopflying** [comment]
Checked trajectory on the ground during taxi. Appears realistic.
As we don't feel accelerations at our desk, it is easy to miss the correct amount of rudder input, which is less of an issue in real life.

**Comment by HHS81** [comment]
The rudder pedals are quite sensitive on the real airplane as well, as I heard. I thinkt that's one of the first lessons for a student, stearing an aircraft on he ground and keeping it on the center line while taxiing.

**Comment by hbeni** [comment]
Thank you all for responding so quickly.
For me here in my desk the c172 and 182 react differently; the 172 way more damped and easier to control.

Is the 172 then not realistic enough?
I had assumed, that ground behaviour is at least in the same ballpark…
For takeoff with the 182, i need roughly 1/3 of rudder only.

**Comment by hbeni** [comment]
> /fdm/jsbsim/fcs/rudder-pos-deg What is the POH saying? Could be mechanically different as well.

I searched and could not find numbers. Also I searched the web.
The full rudder deflection angle is more than the 172p Simulation. That may explain the difference in behaviour.

**Comment by HHS81** [comment]
> > /fdm/jsbsim/fcs/rudder-pos-deg What is the POH saying? Could be mechanically different as well.
> 
> I searched and could not find numbers. Also I searched the web. The full rudder deflection angle is more than the 172p Simulation. That may explain the difference in behaviour.

Yes, the C182 has more rudder deflection angle. It is a bigger, heavier aircraft. You get all numbers from the type certicifation sheets like: file:///C:/Users/Heiko/Downloads/EASA.IM_.A.052.pdf
But there is something which might explain it: the sheet states full rudder deflection 24° parallel to 0.00 W.L line, and 27° perpendicúlar to the hinge line. Since JSBSim doesn't use the hinge line as I think, we might should use the 24° deflection angle

**Comment by HHS81** [comment]
@ysopflying Or does JSBSim uses the hinge line as reference, or a perpedicular hinge line?

**Comment by ysopflying** [comment]
As JSBsim control surface effects are not part of the core, but more of the aircraft specific formula set, it is more about industry standard of deflection angles.

Normally a rudder deflection is measured as an angle around the hinge axis. This hinge axis can be oriented at any angle relative to the aircraft reference system. 
So max deflection should be measured the same way. Hence in my humble opionion 27°.

**Comment by hbeni** [comment]
Thank you for verification.

so we will close this as wontfix?

**Comment by hbeni** [comment]
@ysopflying maybe, when you have data already at hand - could you also peek at #517 and #520 ?

**Comment by ysopflying** [comment]
> so we will close this as wontfix?

Open for discussion. We need more real stick time!

I'd would leave this as it is, as behavior appears normal. A bit of mechanical damping is certainly beneficial.

Open to research is, if it is possible, that the cldr (roll moment due to rudder) at full deflection can overpower clda (roll moment due to aileron) at full deflection.
We need more stick time (with nobody watching.)!

**Comment by ysopflying** [comment]
> @ysopflying maybe, when you have data already at hand - could you also peek at #517 and #520 ?

No data for these issues. A bit of thought posted for the pitching up. Will dive into it deeper later. 
For the engine issue I am not an expert. We would need a good iteration to solve this.

**Comment by TheFGFSEagle** [comment]
> We need more stick time 

There is a C182 based at the nearest airstrip - if I ever get a chance of flying in it, what should I pay attention to, what do you need ?

> (with nobody watching.)!

Why ?

**Comment by ysopflying** [comment]
For sure @hbeni has a long list for this!

Just because, when an airplane owner gives you the yoke of his precious toy, it might not be the best idea say "Hold your beer, I just need some FDM data" and throw it into high speed dives, spins, inverted spins.....

Joking aside, there is a lot, which can be done with a camera and the sensors in the cellphone.

**Comment by hbeni** [comment]
> For sure @hbeni has a long list for this!

ohhhhh sure! We can start at the gauges behaviour when applying power, when the Engine starts and when is operating.
Or actual displayed data at an engine runup :)
Actuaylly a highres video of the instruments at various flight (and preflight) situations would be awesome.

**Comment by hbeni** [comment]
But for getting data of this, maybe a video of the pedals durint taxi and takeoff should suffice.

**Comment by ysopflying** [comment]
Suggest to open up an improvement issue "real pilot feedback", so people can tune in on various subjects and the wish list can go there.

**Comment by hbeni** [comment]
Good idea, i just drafted something.
Will go trough my scattered list and add as i find findings…

**Comment by hbeni** [comment]
So catching up on this again.

>A bit of mechanical damping is certainly beneficial.

OK, just merged ee6e31ed4c5 and ported it from the c172p.

> But there is something which might explain it: the sheet states full rudder deflection 24° parallel to 0.00 W.L line, and 27° perpendicular to the hinge line. Since JSBSim doesn't use the hinge line as I think, we might should use the 24° deflection angle

But wouldn't that mean, that jsbsim uses the tilted 27° for calculations where the formulas currently assume 0° hinge line? So ending up in too big values?
But the comments also explicitely state `Perpendicular to hinge line`, so 27 seems correct:
https://github.com/HHS81/c182s/blob/560a99cc7502bd96f504df021f4b0e02d637e039/c182s.xml#L955-L963



I just tried out 24° vs. 27°; and it seems it does not matter much.
With the damping kinematic, it is already better for me. Maybe it was just jitter from the rudder pedals making the FDM confused or so?

**Comment by ysopflying** [comment]
It would matter 23/27= abt.15% 
Kinematic damping is certainly beneficial, considering the rudder needs to be moved mechanically.
Reference axis needs to be same as in the source of the data.

**Comment by hbeni** [comment]
See other discussions; tldr: port lag filter from PA28 for rudder, aileron and elevator.
https://github.com/HHS81/c182s/pull/582#issuecomment-2030922438
